import yfinance as yf
import pandas as pd
import os
from datetime import datetime

smallcap_tickers = [
    "AARTIIND.NS",
    "ABCAPITAL.NS",
    "ACE.NS",
    "AEGISCHEM.NS",
    "AJANTPHARM.NS",
    "ALKEM.NS",
    "AMARAJABAT.NS",
    "ANGELONE.NS",
    "APTUS.NS",
    "ATUL.NS",
    "AETHER.NS",
    "BALAMINES.NS",
    "BASF.NS",
    "BAYERCROP.NS",
    "BDL.NS",
    "BEML.NS",
    "BLS.NS",
    "BLUESTARCO.NS",
    "BRIGADE.NS",
    "CANFINHOME.NS",
    "CARBORUNIV.NS",
    "CASTROLIND.NS",
    "CEATLTD.NS",
    "CENTRALBK.NS",
    "CENTURYTEX.NS",
    "CENTURYPLY.NS",
    "CHAMBLFERT.NS",
    "CHALET.NS",
    "CHOLAHLDNG.NS",
    "CIEINDIA.NS",
    "COROMANDEL.NS",
    "CREDITACC.NS",
    "CYIENT.NS",
    "DCMSHRIRAM.NS",
    "ECLERX.NS",
    "EIDPARRY.NS",
    "ELGIEQUIP.NS",
    "EMAMILTD.NS",
    "ENDURANCE.NS",
    "ENGINERSIN.NS",
    "EQUITASBNK.NS",
    "ERIS.NS",
    "EXIDEIND.NS",
    "FDC.NS",
    "FIEMIND.NS",
    "FINCABLES.NS",
    "FINPIPE.NS",
    "FLUOROCHEM.NS",
    "GAEL.NS",
    "GALAXYSURF.NS",
    "GARFIBRES.NS",
    "GLAXO.NS",
    "GLS.NS",
    "GNFC.NS",
    "GODFRYPHLP.NS",
    "GPPL.NS",
    "GRANULES.NS",
    "GRAPHITE.NS",
    "GESHIP.NS",
    "GSPL.NS",
    "GUJALKALI.NS",
    "HBLPOWER.NS",
    "HEG.NS",
    "HFCL.NS",
    "HGINFRA.NS",
    "HINDCOPPER.NS",
    "HINDPETRO.NS",
    "HINDOILEXP.NS",
    "IIFLWAM.NS",
    "IONEXCHANG.NS",
    "ISGEC.NS",
    "IEX.NS",
    "INDIACEM.NS",
    "INDIAMART.NS",
    "INDIGOPNTS.NS",
    "INTELLECT.NS",
    "IPCALAB.NS",
    "IRB.NS",
    "ISEC.NS",
    "ITI.NS",
    "JAMNAAUTO.NS",
    "JBCHEPHARM.NS",
    "JINDALSAW.NS",
    "JKCEMENT.NS",
    "JKLAKSHMI.NS",
    "JKPAPER.NS",
    "JMFINANCIL.NS",
    "JSL.NS",
    "JTEKTINDIA.NS",
    "JUBLINGREA.NS",
    "JYOTHYLAB.NS",
    "KAJARIACER.NS",
    "KALPATPOWR.NS",
    "KANSAINER.NS",
    "KEC.NS",
    "KIRLOSENG.NS",
    "KIRLOSBROS.NS",
    "KNRCON.NS",
    "KPRMILL.NS",
    "KRBL.NS",
    "KSB.NS",
    "LAXMIMACH.NS",
    "LEMONTREE.NS",
    "LINDEINDIA.NS",
    "MANAPPURAM.NS",
    "MASTEK.NS",
    "MAZDOCK.NS",
    "MCX.NS",
    "METROPOLIS.NS",
    "MIDHANI.NS",
    "MMTC.NS",
    "MOIL.NS",
    "MOTILALOFS.NS",
    "MRPL.NS",
    "MSTCLTD.NS",
    "NATCOPHARM.NS",
    "NAUKRI.NS",
    "NAVINFLUOR.NS",
    "NBCC.NS",
    "NCC.NS",
    "NETWORK18.NS",
    "NIACL.NS",
    "NILKAMAL.NS",
    "NLCINDIA.NS",
    "NTPC.NS",
    "NURECA.NS",
    "OLECTRA.NS",
    "ORIENTELEC.NS",
    "PCBL.NS",
    "PDSL.NS",
    "PGHH.NS",
    "POLYMED.NS",
    "PPLPHARMA.NS",
    "PRSMJOHNSN.NS",
    "QUESS.NS",
    "RADICO.NS",
    "RAJESHEXPO.NS",
    "RALLIS.NS",
    "RITES.NS",
    "ROSSARI.NS",
    "ROUTE.NS",
    "RVNL.NS",
    "SANOFI.NS",
    "SAPPHIRE.NS",
    "SCHAEFFLER.NS",
    "SHILPAMED.NS",
    "SHOPERSTOP.NS",
    "SKFINDIA.NS",
    "SPARC.NS",
    "STARCEMENT.NS",
    "STLTECH.NS",
    "SWANENERGY.NS",
    "SWSOLAR.NS",
    "TANLA.NS",
    "TATAINVEST.NS",
    "TCIEXP.NS",
    "TDPOWERSYS.NS",
    "TEAMLEASE.NS",
    "THERMAX.NS",
    "TIMKEN.NS",
    "TITAGARH.NS",
    "TRIDENT.NS",
    "TRITURBINE.NS",
    "TTKPRESTIG.NS",
    "TV18BRDCST.NS",
    "TVSSCS.NS",
    "UCOBANK.NS",
    "UJJIVANSFB.NS",
    "UNOMINDA.NS",
    "VAIBHAVGBL.NS",
    "VGUARD.NS",
    "VINATIORGA.NS",
    "VSTIND.NS",
    "WELCORP.NS",
    "WHIRLPOOL.NS",
    "ZENSARTECH.NS",
    "ZFCVINDIA.NS",
    "HDFCSML250.NS",
]

START_DATE = "2020-01-01"
END_DATE = datetime.today().strftime("%Y-%m-%d")
OUTPUT_FOLDER = "smallcap_data"
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

all_data = []
for ticker in smallcap_tickers:
    try:
        print(f"Downloading {ticker}")
        df = yf.download(ticker, start=START_DATE, end=END_DATE, interval="1d", auto_adjust=False, progress=False)
        if df.empty:
            print(f"No data for {ticker}")
            continue
        df.reset_index(inplace=True)
        file_path = os.path.join(OUTPUT_FOLDER, f"{ticker}.csv")
        df.to_csv(file_path, index=False)
        df["Ticker"] = ticker
        all_data.append(df)
    except Exception as e:
        print(f"Error downloading {ticker}: {e}")

if all_data:
    combined_df = pd.concat(all_data)
    combined_df.to_csv(os.path.join(OUTPUT_FOLDER, "SMALLCAP250_ALL.csv"), index=False)
    print("Combined CSV saved.")
print("Download Completed.")
