import os
import sys

# Add project root to path so pages can import rs_common
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

from rs_common import render_rs_dashboard

# =========================
# Nifty Smallcap 250 tickers (Official list - April 2026)
# =========================

smallcap250_tickers = [
    "360ONE.NS", "AARTIIND.NS", "AAVAS.NS", "ABSLAMC.NS", "ACE.NS",
    "AEGISLOG.NS", "AFFLE.NS", "ALEMBICLTD.NS", "ALKYLAMINE.NS", "ALOKINDS.NS",
    "ARE&M.NS", "AMBER.NS", "ANANDRATHI.NS", "ANANTRAJ.NS", "ANGELONE.NS",
    "APARINDS.NS", "APTUS.NS", "ASAHIINDIA.NS", "ASTERDM.NS", "ASTRAZEN.NS",
    "ATUL.NS", "AVANTIFEED.NS", "AWL.NS", "BBTC.NS", "BALAMINES.NS",
    "BALRAMCHIN.NS", "BASF.NS", "BATAINDIA.NS", "BEML.NS", "BSOFT.NS",
    "BIRLACORPN.NS", "BLS.NS", "BLUEDART.NS", "BLUESTARCO.NS", "BRIGADE.NS",
    "CAMPUS.NS", "CANFINHOME.NS", "CAPLIPOINT.NS", "CASTROLIND.NS", "CAMS.NS",
    "CCL.NS", "CDSL.NS", "CENTRALBK.NS", "CENTURYPLY.NS", "CENTEXT.NS",
    "CERA.NS", "CESC.NS", "CEATLTD.NS", "CGCL.NS", "CHAMBLFERT.NS",
    "CHALET.NS", "CHEMPLASTS.NS", "CHENNPETRO.NS", "CLEAN.NS", "CRAFTSMAN.NS",
    "CREDITACC.NS", "CROMPTON.NS", "CUB.NS", "CYIENT.NS", "DATAPATTNS.NS",
    "DBREALTY.NS", "DEEPAKFERT.NS", "DELHIVERY.NS", "DEVYANI.NS", "EASEMYTRIP.NS",
    "ECLERX.NS", "EIHOTEL.NS", "EIDPARRY.NS", "ELECON.NS", "ELGIEQUIP.NS",
    "ENGINERSIN.NS", "EQUITASBNK.NS", "ERIS.NS", "FINEORG.NS", "FINCABLES.NS",
    "FSL.NS", "GESHIP.NS", "GILLETTE.NS",
    "GLENMARK.NS", "GMDCLTD.NS", "GNFC.NS", "GOCLCORP.NS", "GODFRYPHLP.NS",
    "GODREJAGRO.NS", "GPPL.NS", "GRANULES.NS", "GRAPHITE.NS", "GRINFRA.NS",
    "GRSE.NS", "GSFC.NS", "GSPL.NS", "GAEL.NS", "HAPPSTMNDS.NS",
    "HEG.NS", "HFCL.NS", "HSCL.NS", "HINDCOPPER.NS", "HOMEFIRST.NS",
    "IFCI.NS", "IEX.NS", "IIFL.NS", "INDIACEM.NS", "INDIAMART.NS",
    "INOXWIND.NS", "INTELLECT.NS", "IRCON.NS", "ITI.NS", "JBMA.NS",
    "JBCHEPHARM.NS", "JKLAKSHMI.NS", "JKTYRE.NS", "JUBLPHARMA.NS", "JUBLINGREA.NS",
    "JUSTDIAL.NS", "JWL.NS", "JYOTHYLAB.NS", "KAJARIACER.NS",
    "KARURVYSYA.NS", "KEC.NS", "KIMS.NS", "KIRLOSENG.NS", "KIRLOSBROS.NS",
    "KNRCON.NS", "KPRMILL.NS", "KSB.NS", "LALPATHLAB.NS", "LATENTVIEW.NS",
    "LAURUSLABS.NS", "LEMONTREE.NS", "MGL.NS", "CIEINDIA.NS", "MAHLIFE.NS",
    "MAHSEAMLES.NS", "MANAPPURAM.NS", "MAPMYINDIA.NS", "MASTEK.NS", "MCX.NS",
    "MEESHO.NS", "METROPOLIS.NS", "MINDACORP.NS", "MMTC.NS", "MOTILALOFS.NS",
    "NH.NS", "NATCOPHARM.NS", "NATIONALUM.NS", "NAVINFLUOR.NS", "NBCC.NS",
    "NCC.NS", "NETWORK18.NS", "NEWGEN.NS", "NUVOCO.NS",
    "OLECTRA.NS", "PNCINFRA.NS", "PCBL.NS", "PFIZER.NS", "PPLPHARMA.NS",
    "PIRAMALFIN.NS", "PNBHOUSING.NS", "POLYMED.NS", "PRAJIND.NS", "PVRINOX.NS",
    "QUESS.NS", "RADICO.NS", "RAILTEL.NS", "RAJESHEXPO.NS", "RAMCOCEM.NS",
    "RATNAMANI.NS", "RAYMOND.NS", "RBLBANK.NS", "RCF.NS", "REDINGTON.NS",
    "RENUKA.NS", "RHIM.NS", "RKFORGE.NS", "ROUTE.NS", "SAMMAANCAP.NS",
    "SANOFI.NS", "SAPPHIRE.NS", "SAREGAMA.NS", "SCI.NS", "SCHNEIDER.NS",
    "SHYAMMETL.NS", "SOBHA.NS", "SONATSOFTW.NS", "SPARC.NS", "SUMICHEM.NS",
    "SWSOLAR.NS", "SYRMA.NS", "TANLA.NS", "TECHNOE.NS", "TEJASNET.NS",
    "TITAGARH.NS", "TRIDENT.NS", "TRIVENI.NS", "TTML.NS", "UCOBANK.NS",
    "UJJIVANSFB.NS", "USHAMART.NS", "UTIAMC.NS", "VARROC.NS", "VTL.NS",
    "MANYAVAR.NS", "VGUARD.NS", "VIJAYA.NS", "VIPIND.NS", "VINATIORGA.NS",
    "WELCORP.NS", "WELSPUNLIV.NS", "WESTLIFE.NS", "WHIRLPOOL.NS", "ZEEL.NS",
    "ZENSARTECH.NS"
]

BENCHMARK = "HDFCSML250.NS"
DATA_FOLDER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "smallcap_data")

render_rs_dashboard(
    title="Nifty Smallcap 250 Relative Strength Dashboard (Small Cap)",
    tickers=smallcap250_tickers,
    benchmark=BENCHMARK,
    data_folder=DATA_FOLDER,
    download_script="data_download_smallcap.py",
)